FROM public.ecr.aws/lambda/python:3.12

# Build deps for mysqlclient.
RUN dnf install -y gcc mariadb-connector-c-devel && dnf clean all

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt
# Install instrumentation libraries matching installed packages (Django, dbapi/MySQL).
RUN opentelemetry-bootstrap -a install

COPY manage.py rds-global-bundle-ca.pem lambda_handler.py ${LAMBDA_TASK_ROOT}/
COPY djaret/ ${LAMBDA_TASK_ROOT}/djaret/
COPY djaret_app/ ${LAMBDA_TASK_ROOT}/djaret_app/

# OTel initialized in-process in lambda_handler.py (the layer's /opt/otel-instrument
# exec wrapper breaks container RIC). The SDK App Signals exporter is OFF — it would
# target a localhost:4316 CloudWatch agent we don't run (connection refused). Instead
# the SDK SigV4-signs OTLP traces straight to the X-Ray endpoint (collector-less),
# and the App Signals service map / RED metrics are generated by the Lambda platform
# from X-Ray Active tracing (service = djaret-lambda-pro). always_on = trace 100%.
ENV DJANGO_SETTINGS_MODULE=djaret.settings \
    OTEL_PYTHON_DISTRO=aws_distro \
    OTEL_PYTHON_CONFIGURATOR=aws_configurator \
    OTEL_PYTHON_DISABLED_INSTRUMENTATIONS=aws-lambda \
    OTEL_SERVICE_NAME=djaret-backend \
    OTEL_AWS_APPLICATION_SIGNALS_ENABLED=false \
    OTEL_TRACES_EXPORTER=otlp \
    OTEL_METRICS_EXPORTER=none \
    OTEL_LOGS_EXPORTER=none \
    OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf \
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://xray.eu-west-1.amazonaws.com/v1/traces \
    OTEL_TRACES_SAMPLER=always_on

CMD ["lambda_handler.handler"]
