sonar.projectKey=djaret
sonar.organization=yarete03

sonar.sources=djaret,djaret_app,lambda_handler.py,manage.py,frontend,Dockerfile,requirements.txt,.dockerignore,.github/workflows/ci-cd.yml
sonar.python.version=3.12

sonar.exclusions=**/migrations/**,staticfiles/**,terraform/**,**/__pycache__/**
