sonar.projectKey=djaret
sonar.organization=yarete03

sonar.sources=djaret,djaret_app,lambda_handler.py,manage.py,frontend,Dockerfile,requirements.txt,.dockerignore,.github/workflows/ci-cd.yml
sonar.tests=djaret_app/tests.py
sonar.python.version=3.12

sonar.exclusions=**/migrations/**,staticfiles/**,terraform/**,**/__pycache__/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=frontend/**,Dockerfile,manage.py,lambda_handler.py,djaret/**,djaret_app/__init__.py,djaret_app/apps.py,djaret_app/admin.py,djaret_app/models.py,**/migrations/**
