sonar.projectKey=djaret
sonar.organization=yarete03

sonar.sources=djaret,djaret_app,lambda_handler.py,manage.py
sonar.python.version=3.12

sonar.exclusions=**/migrations/**,staticfiles/**,frontend/**,terraform/**,**/__pycache__/**
