name: Django CI-CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: djaret-ecr-pro
  ECR_REGISTRY: 884916644426.dkr.ecr.eu-west-1.amazonaws.com
  S3_BUCKET: djaret-s3-pro

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::884916644426:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Upload static files to S3
        run: |
          aws s3 sync staticfiles/ s3://$S3_BUCKET/static/ --delete

      - name: Purge CloudFront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id E373BG2H9HPN4J \
          --paths "/static/*"

      - name: Generate image tag
        id: vars
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY/djaret:$SHORT_SHA .

      - name: Push image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/djaret:$SHORT_SHA

      - name: Update Lambda image
        run: |
          aws lambda update-function-code \
            --function-name djaret-lambda-pro \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY/djaret:$SHORT_SHA